### ISSUE TITLE
AttributeError: 'int' object has no attribute 'price' in amber_api.py after upgrading to 0.9.0

### ISSUE THREAD

**Issue by dp-eng** [4tiernan/mpc_energy#150]
**Version:** MPC Energy 0.9.0 (regression from 0.8.0)

**Environment:** Home Assistant OS add-on, Amber Electric integration (native HA integration, entities functioning normally)

**Description:**
After upgrading MPC Energy from 0.8.0 to 0.9.0, the app repeatedly crashes into "safe mode" every ~30 seconds with the following traceback:

```
File "/app/main.py", line 466, in main_loop_code
    price_data = amber.get_data(partial_update=True, ..., sim_end=mpc.sim_end)
File "/app/External_Interfaces/amber_api.py", line 417, in get_data
    general_max_price = max((pf.price for pf in general_price_forecast[:24]), default=0)
File "/app/External_Interfaces/amber_api.py", line 417, in <genexpr>
    general_max_price = max((pf.price for pf in general_price_forecast[:24]), default=0)
AttributeError: 'int' object has no attribute 'price'
```

**Investigation:**
- Confirmed Amber Electric's native HA integration is functioning correctly - sensor.home_general_price and sensor.home_general_forecast both report valid current data with all expected attributes (per_kwh, spot_per_kwh, renewables, descriptor, etc.).
- Amber's forecast list items use field per_kwh, not price, so amber_api.py clearly transforms these into its own internal object before this calculation runs.
- Some entries in general_price_forecast[:24] are plain int rather than the expected object, causing .price access to fail. This suggests the list is being padded/defaulted with raw integers (e.g., 0) for missing/short forecast slots rather than proper forecast objects.
- This appears to be a new/reintroduced regression in 0.9.0 - the changelog lists "Added Generic Energy Retailer Option" and "Added ability to handle new and old flow data timestamps," which likely altered forecast-list construction and broke this Amber-specific code path.

**Steps to reproduce:**
1. Configure MPC Energy with Amber Electric as the retailer.
2. Update to version 0.9.0.
3. Observe repeated crash/safe-mode loop in the add-on log approximately every 30 seconds.

**Impact:** App continuously falls into safe mode and cannot generate a battery/EV optimisation plan while the Amber price forecast is unavailable.
